import { Product, ResearchPaper, ChemicalStep, Stat } from '@/types';

export const products: Product[] = [
  {
    id: 'p1',
    name: 'Pure Chitosan Powder',
    scientificName: 'Poly-(1→4)-2-amino-2-deoxy-β-D-glucan',
    description: 'Food-grade chitosan derived from shrimp shell waste via enzymatic deacetylation. 85-90% degree of deacetylation, suitable for agricultural and food applications.',
    price: 45.00,
    category: 'Raw Material',
    image: '/api/placeholder/400/300',
    badge: 'Best Seller',
    inStock: true,
    purity: '≥95%',
    concentration: '85-90% DDA',
    details: [
      'Degree of Deacetylation: 85–90%',
      'Molecular Weight: 200–400 kDa',
      'Viscosity: 200–800 mPa·s',
      'Ash Content: <1%',
      'Moisture: <10%',
      'Food-grade certified',
    ],
  },
  {
    id: 'p2',
    name: 'Chitosan–Metformin Capsules',
    scientificName: 'Chitosan-Metformin HCl Controlled Release',
    description: 'Innovative controlled-release capsules combining pharmaceutical-grade chitosan with Metformin HCl for enhanced bioavailability and reduced GI side effects. Research formulation.',
    price: 120.00,
    category: 'Pharmaceutical',
    image: '/api/placeholder/400/300',
    badge: 'New',
    inStock: true,
    purity: '99.9%',
    concentration: '500mg Metformin / 150mg Chitosan',
    details: [
      'Metformin HCl: 500 mg/capsule',
      'Chitosan (pharmaceutical grade): 150 mg',
      'Controlled-release matrix technology',
      'Reduced GI adverse effects vs. standard tablets',
      'Enhanced mucoadhesion for prolonged absorption',
      'pH-sensitive coating: dissolves at pH 6.8–7.4',
      'Bioavailability improvement: up to 30% vs. standard',
    ],
  },
  {
    id: 'p3',
    name: 'Natural Food Preservative',
    scientificName: 'Chitosan Antimicrobial Solution 2% w/v',
    description: 'Ready-to-use 2% chitosan solution with proven antimicrobial efficacy against Staphylococcus aureus, E. coli, and Salmonella. Extends shelf life by 3–5 days naturally.',
    price: 35.00,
    category: 'Food & Agriculture',
    image: '/api/placeholder/400/300',
    inStock: true,
    concentration: '2% w/v in 1% acetic acid',
    details: [
      'Concentration: 2% w/v chitosan',
      'Solvent: 1% glacial acetic acid',
      'MIC vs S. aureus: 0.5 mg/mL',
      'MIC vs E. coli: 1.0 mg/mL',
      'Shelf-life extension: 3–5 days',
      'GRAS status (FDA 21 CFR)',
      'Ready-to-spray formulation',
    ],
  },
  {
    id: 'p4',
    name: 'Agricultural Chitosan Spray',
    scientificName: 'Oligomeric Chitosan Solution (10 kDa)',
    description: 'Low-molecular-weight oligomeric chitosan spray that elicits plant defense responses, improves germination rates by 25%, and reduces fungal infection in crops.',
    price: 28.00,
    category: 'Food & Agriculture',
    image: '/api/placeholder/400/300',
    inStock: true,
    concentration: '0.5% w/v',
    details: [
      'Molecular weight: 10–20 kDa (oligomeric)',
      'Concentration: 0.5% w/v',
      'pH: 5.5–6.0',
      'Germination enhancement: +25%',
      'Root development: +30% biomass',
      'Fungicide alternative (biostimulant)',
      'Approved for organic farming (EU Reg. 2018/848)',
    ],
  },
  {
    id: 'p5',
    name: 'Chitin Raw Powder',
    scientificName: 'Poly-(1→4)-2-acetamido-2-deoxy-β-D-glucose',
    description: 'High-purity α-chitin extracted from shrimp exoskeletons via acid demineralization and alkali deproteinization. Suitable for research and industrial applications.',
    price: 55.00,
    category: 'Raw Material',
    image: '/api/placeholder/400/300',
    inStock: true,
    purity: '≥90%',
    details: [
      'Form: α-chitin (crustacean source)',
      'Purity: ≥90%',
      'Ash content: <2%',
      'Protein content: <3%',
      'Particle size: 100–200 mesh',
      'Degree of acetylation: >80%',
    ],
  },
  {
    id: 'p6',
    name: 'Chitosan Water Filter Kit',
    scientificName: 'Chitosan Coagulant–Flocculant System',
    description: 'Water purification kit using chitosan as a natural coagulant–flocculant for removal of heavy metals (Pb²⁺, Cu²⁺, Cd²⁺), turbidity, and bacteria from wastewater.',
    price: 75.00,
    category: 'Environmental',
    image: '/api/placeholder/400/300',
    badge: 'Eco Choice',
    inStock: true,
    details: [
      'Pb²⁺ removal efficiency: >95%',
      'Cu²⁺ removal: >90%',
      'Turbidity reduction: >99%',
      'Effective pH range: 5–7',
      'Dosage: 10–50 mg/L water',
      'Includes 100g chitosan flakes + instructions',
      'Reusable column design',
    ],
  },
];

export const researchPapers: ResearchPaper[] = [
  {
    id: 'r1',
    title: 'Chitin and Chitosan: Properties and Applications',
    authors: ['Rinaudo, M.'],
    journal: 'Progress in Polymer Science',
    year: 2006,
    doi: '10.1016/j.progpolymsci.2006.06.001',
    abstract: 'Comprehensive review of chitin and chitosan biopolymers covering extraction from crustacean shells, chemical modification, and industrial applications in biomedicine, agriculture, and food preservation. Discusses degree of deacetylation (DD) measurement by ¹H NMR and IR spectroscopy.',
    tags: ['Chitin', 'Chitosan', 'Extraction', 'Applications', 'Biopolymer'],
    source: 'ScienceDirect',
  },
  {
    id: 'r2',
    title: 'Chitin Extraction from Shrimp Shells: Effect of Process Parameters on Physicochemical Properties',
    authors: ['No, H.K.', 'Meyers, S.P.'],
    journal: 'Journal of Agricultural and Food Chemistry',
    year: 1995,
    doi: '10.1021/jf00055a041',
    abstract: 'Systematic study of demineralization (HCl concentration 0.5–2 M), deproteinization (NaOH 1–5%), and decolorization (KMnO₄) conditions for chitin extraction from Penaeus shrimp shells. Optimal: 1M HCl 30 min + 1N NaOH 90°C.',
    tags: ['Extraction', 'Shrimp Shell', 'Demineralization', 'Deproteinization'],
    source: 'PubMed',
  },
  {
    id: 'r3',
    title: 'Deacetylation of Chitin: Critical Parameters, Properties and Applications',
    authors: ['Younes, I.', 'Rinaudo, M.'],
    journal: 'Marine Drugs',
    year: 2015,
    doi: '10.3390/md13031133',
    abstract: 'Analysis of chitin deacetylation to chitosan under various NaOH concentrations (40–60%), temperatures (80–140°C), and reaction times. Heterogeneous alkaline deacetylation at 50% NaOH, 100°C achieves DD >80% in two cycles.',
    tags: ['Deacetylation', 'Chitosan', 'NaOH', 'Temperature', 'Degree of Deacetylation'],
    source: 'PubMed',
  },
  {
    id: 'r4',
    title: 'Chitosan as Antimicrobial Agent: Applications and Mode of Action',
    authors: ['Kong, M.', 'Chen, X.G.', 'Xing, K.', 'Park, H.J.'],
    journal: 'International Journal of Food Microbiology',
    year: 2010,
    doi: '10.1016/j.ijfoodmicro.2010.09.012',
    abstract: 'Review of chitosan antimicrobial activity against bacteria and fungi. MIC values: E. coli 1 mg/mL, S. aureus 0.5 mg/mL. Mechanism involves disruption of cell membrane via electrostatic interaction with negatively charged phospholipids at pH < 6.5.',
    tags: ['Antimicrobial', 'Food Preservation', 'MIC', 'Mechanism'],
    source: 'PubMed',
  },
  {
    id: 'r5',
    title: 'Chitosan-Based Drug Delivery Systems: A Mini-Review of Progress in the Last Decade',
    authors: ['Azuma, K.', 'Osaki, T.', 'Minami, S.', 'Okamoto, Y.'],
    journal: 'Glycoconjugate Journal',
    year: 2015,
    doi: '10.1007/s10719-015-9608-4',
    abstract: 'Mucoadhesive and controlled-release properties of chitosan for oral drug delivery. Chitosan–Metformin matrices show 4-fold reduction in burst release and 30% increase in bioavailability compared to standard tablets. pH-sensitive swelling at intestinal pH 6.8.',
    tags: ['Drug Delivery', 'Metformin', 'Mucoadhesive', 'Controlled Release', 'Chitosan'],
    source: 'PubMed',
  },
  {
    id: 'r6',
    title: 'Global Shrimp Production and Waste: Economic and Environmental Assessment',
    authors: ['FAO Fisheries Division'],
    journal: 'FAO Technical Paper',
    year: 2022,
    doi: 'FAO/2022/shrimp-waste',
    abstract: 'Global shrimp production reached 9.4 million metric tons in 2021. Shell waste constitutes 40–50% of total weight. Annual chitin content of global shrimp waste: 150,000–180,000 metric tons. Environmental impact: 2.3 million tons of untreated shell waste discharged annually.',
    tags: ['Global Production', 'Environmental Impact', 'Statistics', 'FAO'],
    source: 'Google Scholar',
  },
  {
    id: 'r7',
    title: 'Heavy Metal Removal Using Chitosan as Biosorbent: Equilibrium, Kinetics and Mechanism',
    authors: ['Babel, S.', 'Kurniawan, T.A.'],
    journal: 'Chemosphere',
    year: 2004,
    doi: '10.1016/j.chemosphere.2004.04.028',
    abstract: 'Chitosan biosorbent removes Pb²⁺ with efficiency >95%, Cu²⁺ 90%, Cd²⁺ 85% at pH 5–6. Langmuir adsorption capacity: 815 mg Pb/g chitosan. Mechanism: chelation of metal ions by amine (–NH₂) and hydroxyl (–OH) groups.',
    tags: ['Water Treatment', 'Heavy Metals', 'Biosorbent', 'Environmental'],
    source: 'ScienceDirect',
  },
];

export const chitinSteps: ChemicalStep[] = [
  {
    step: 1,
    name: 'Collection & Washing',
    reagent: 'Distilled Water',
    temperature: 'Room Temp (25°C)',
    duration: '30 minutes',
    description: 'Fresh shrimp shells are collected, sorted, and thoroughly washed with distilled water to remove flesh, sand, and contaminants. Shells are then dried at 60°C for 24h.',
    color: '#4ecdc4',
    equation: 'Shrimp Shell → Dried Shell Powder (60°C, 24h)',
  },
  {
    step: 2,
    name: 'Demineralization',
    reagent: '1M Hydrochloric Acid (HCl)',
    temperature: '25°C (Room Temp)',
    duration: '30 minutes',
    pH: '1–2',
    description: 'Calcium carbonate (CaCO₃) and calcium phosphate minerals in the shells are dissolved by reaction with HCl. The ratio is 1:10 (shell:acid, w/v). Produces CO₂ bubbles.',
    equation: 'CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂↑',
    color: '#f5c842',
  },
  {
    step: 3,
    name: 'Deproteinization',
    reagent: '1N Sodium Hydroxide (NaOH)',
    temperature: '90°C',
    duration: '90 minutes',
    pH: '12–14',
    description: 'Proteins bound to the chitin matrix are hydrolyzed and removed using hot alkaline solution. The shell residue is filtered and washed to neutral pH 7.',
    equation: 'Protein + NaOH → Amino Acids (soluble) + Crude Chitin',
    color: '#ff6b6b',
  },
  {
    step: 4,
    name: 'Decolorization (Optional)',
    reagent: '0.5% KMnO₄ + 0.05M Oxalic Acid',
    temperature: '25°C',
    duration: '1–2 hours',
    description: 'Residual pigments (astaxanthin, carotenoids) are oxidized by KMnO₄ to produce white chitin. Excess KMnO₄ removed by oxalic acid bleaching.',
    equation: 'Carotenoids + KMnO₄ → Colorless oxidized pigments',
    color: '#a29bfe',
  },
  {
    step: 5,
    name: 'Pure Chitin Obtained',
    reagent: 'Distilled Water (final wash)',
    temperature: '60°C (drying)',
    duration: '24 hours',
    description: 'White, odorless chitin powder (α-chitin crystalline form) is obtained. Purity ≥90%, ash <2%, protein <3%. Yield: approximately 15–25% of dry shell weight.',
    equation: 'Result: α-chitin [C₈H₁₃NO₅]ₙ — White powder, purity ≥90%',
    color: '#00b4d8',
  },
];

export const chitosanSteps: ChemicalStep[] = [
  {
    step: 1,
    name: 'Chitin Input',
    reagent: 'Pure α-Chitin',
    temperature: '25°C',
    duration: 'N/A',
    description: 'Starting material is purified chitin powder (≥90% purity). The degree of acetylation (DA) is typically 80–95%, meaning 80–95% of the glucosamine units carry acetyl groups.',
    equation: 'α-Chitin: [C₈H₁₃NO₅]ₙ, DA ≈ 80–95%',
    color: '#4ecdc4',
  },
  {
    step: 2,
    name: 'Alkali Deacetylation',
    reagent: '50% NaOH (w/w)',
    temperature: '100–120°C',
    duration: '2–4 hours (repeated 2×)',
    pH: '>13',
    description: 'Chitin is submerged in concentrated NaOH under nitrogen atmosphere to prevent oxidative degradation. The acetyl groups (–COCH₃) are hydrolyzed, exposing free amine groups (–NH₂). Two reaction cycles are typically required to achieve DD >85%.',
    equation: '[C₈H₁₃NO₅]ₙ + NaOH → [C₆H₁₁NO₄]ₙ + CH₃COONa\n(Chitin → Chitosan + Sodium Acetate)',
    color: '#f5c842',
  },
  {
    step: 3,
    name: 'Neutralization & Washing',
    reagent: 'Distilled Water',
    temperature: '25°C',
    duration: '30–60 minutes',
    pH: '7',
    description: 'The deacetylated product is filtered and washed repeatedly with distilled water until neutral pH is achieved (pH meter verified). Residual NaOH must be completely removed.',
    equation: 'Chitosan-NaOH mixture → Neutral Chitosan + Wash Water (pH 7)',
    color: '#ff6b6b',
  },
  {
    step: 4,
    name: 'Drying & Milling',
    reagent: 'Hot Air Oven',
    temperature: '60°C',
    duration: '24 hours',
    description: 'Washed chitosan is dried at 60°C to moisture content <10%. The dried product is ground to desired particle size (100–200 mesh) using a ball mill.',
    equation: 'Wet Chitosan (≈80% moisture) → Chitosan Powder (<10% moisture)',
    color: '#a29bfe',
  },
  {
    step: 5,
    name: 'Quality Control',
    reagent: '1% Acetic Acid (solubility test)',
    temperature: '25°C',
    duration: '30 minutes',
    description: 'DD is measured by ¹H NMR or potentiometric titration. Chitosan (DD >60%) is soluble in 1% acetic acid, distinguishing it from chitin. Viscosity measured at 1% solution in 1% AcOH.',
    equation: 'Chitosan [C₆H₁₁NO₄]ₙ: DD = 85–90%, MW = 200–400 kDa, soluble in 1% AcOH',
    color: '#00b4d8',
  },
];

export const globalStats: Stat[] = [
  { label: 'Global Shrimp Production', value: '9.4', unit: 'Million Metric Tons/yr', trend: '+3.2%', icon: '🦐' },
  { label: 'Shell Waste Generated', value: '3.8', unit: 'Million MT/yr', trend: '+2.8%', icon: '♻️' },
  { label: 'Chitin Content in Shells', value: '20–30', unit: '% dry weight', trend: 'Stable', icon: '🧪' },
  { label: 'Untreated Waste Discharged', value: '2.3', unit: 'Million MT/yr', trend: '-1.1%', icon: '⚠️' },
  { label: 'Chitosan Market Size (2024)', value: '$1.2', unit: 'Billion USD', trend: '+8.5%', icon: '📈' },
  { label: 'CO₂ Equivalent from Waste', value: '4.7', unit: 'Million Tons CO₂e', trend: '-2.0%', icon: '🌍' },
];

export const productionData = [
  { year: '2018', production: 7.8, waste: 3.1, chitin: 0.6 },
  { year: '2019', production: 8.1, waste: 3.3, chitin: 0.65 },
  { year: '2020', production: 8.4, waste: 3.4, chitin: 0.68 },
  { year: '2021', production: 9.1, waste: 3.6, chitin: 0.72 },
  { year: '2022', production: 9.4, waste: 3.8, chitin: 0.76 },
  { year: '2023', production: 9.7, waste: 3.9, chitin: 0.78 },
  { year: '2024', production: 10.1, waste: 4.0, chitin: 0.82 },
];

export const environmentalImpact = [
  { category: 'Methane Emissions', value: 35, color: '#ff6b6b' },
  { category: 'Water Pollution', value: 28, color: '#fca03d' },
  { category: 'Soil Degradation', value: 20, color: '#f5c842' },
  { category: 'Marine Eutrophication', value: 17, color: '#00b4d8' },
];

export const chitosanApplications = [
  { name: 'Pharmaceutical', value: 32, color: '#f5c842' },
  { name: 'Agriculture', value: 24, color: '#4ecdc4' },
  { name: 'Food & Beverage', value: 21, color: '#ff6b6b' },
  { name: 'Water Treatment', value: 15, color: '#00b4d8' },
  { name: 'Cosmetics', value: 8, color: '#a29bfe' },
];

export const teamMembers = [
  { name: 'Dr. Ahmed Hassan', role: 'Project Lead & Biochemist', department: 'Chemistry Dept.', avatar: '👨‍🔬' },
  { name: 'Nour El-Din Mohamed', role: 'Chemical Engineer', department: 'Engineering Dept.', avatar: '👩‍💼' },
  { name: 'Sara Ibrahim', role: 'Pharmaceutical Researcher', department: 'Pharmacy Dept.', avatar: '👩‍🔬' },
  { name: 'Khaled Youssef', role: 'Environmental Scientist', department: 'Science Dept.', avatar: '👨‍💼' },
  { name: 'Mariam Tarek', role: 'Business Development', department: 'Commerce Dept.', avatar: '👩‍💻' },
  { name: 'Omar Sayed', role: 'Marketing & Outreach', department: 'Commerce Dept.', avatar: '👨‍💻' },
];
